### ISSUE TITLE
SSL certificate on jupyterhub.cancercollaboratory.org expiring soon

### ISSUE THREAD

**Issue by jmimico** [icgc-dcc/issues-tracker#5]
Please check certificate renewal automation as the cert should never get this close to expiry

**Comment by d8660091** [comment]
* */12 * * * root test -x /usr/bin/certbot && certbot renew >> /home/ubuntu/cert.log && test /etc/letsencrypt/live/jupyterhub.cancercollaboratory.org/cert.pem -nt /home/jupyterhub/secrets/ssl/cert.pem && cp /etc/letsencrypt/live/jupyterhub.cancercollaboratory.org/cert.pem /home/jupyterhub/secrets/ssl/cert.pem && cd /home/jupyterhub/docker && source /home/jupyterhub/config/jupyterhub.env && docker-compose restart hub
